<a href="https://colab.research.google.com/github/Swinalwaghmare/Deep-Learning/blob/main/backpropagation_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Backpropagation with classification from scratch

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [ ]:
df

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [ ]:
def initialize_parameters(layer_dims):

  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1, L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))

  return parameters

In [ ]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [ ]:
# utility function
def sigmoid(Z):

  A = 1 / (1 + np.exp(-Z))

  return A

In [ ]:
def linear_forward(A_prev, W, b):

  Z = np.dot(W.T, A_prev) + b

  A = sigmoid(Z)

  return A

In [ ]:
#  L - Layer feed forward

def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2

  for l in range(1, L + 1):
    A_prev = A
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]

    A = linear_forward(A_prev, Wl, bl)

  return A, A_prev

In [ ]:
def update_parameters(parameters, y, y_hat, A1, X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.0001 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))

In [ ]:
X = df[['cgpa','profile_score']].values[0].reshape(2,1)
y = df[['placed']].values[0][0]


parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print("Loss for this student - ",-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.613402628898913


{'W1': array([[0.10000513, 0.10000513],
        [0.10000513, 0.10000513]]),
 'b1': array([[6.41054186e-07],
        [6.41054186e-07]]),
 'W2': array([[0.10003815],
        [0.10003815]]),
 'b2': array([[0.100084]])}

In [ ]:
X = df[['cgpa','profile_score']].values[1].reshape(2,1)
y = df[['placed']].values[1][0]


parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print("Loss for this student - ",-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.613402628898913


{'W1': array([[0.10000449, 0.10000577],
        [0.10000449, 0.10000577]]),
 'b1': array([[6.41054186e-07],
        [6.41054186e-07]]),
 'W2': array([[0.10003815],
        [0.10003815]]),
 'b2': array([[0.100084]])}

In [ ]:
X = df[['cgpa','profile_score']].values[2].reshape(2,1)
y = df[['placed']].values[2][0]


parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print("Loss for this student - ",-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.7798063059256977


{'W1': array([[0.09999546, 0.09999244],
        [0.09999546, 0.09999244]]),
 'b1': array([[-7.56487203e-07],
        [-7.56487203e-07]]),
 'W2': array([[0.09995495],
        [0.09995495]]),
 'b2': array([[0.0999008]])}

In [ ]:
X = df[['cgpa','profile_score']].values[3].reshape(2,1)
y = df[['placed']].values[3][0]


parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print("Loss for this student - ",-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

Loss for this student -  0.768922894759937


{'W1': array([[0.09999473, 0.09999473],
        [0.09999473, 0.09999473]]),
 'b1': array([[-1.05438563e-06],
        [-1.05438563e-06]]),
 'W2': array([[0.09996078],
        [0.09996078]]),
 'b2': array([[0.09990713]])}

In [ ]:
## Epoch implementation

parameters = initialize_parameters([2,2,1])
epochs = 50

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1)
    y = df[['placed']].values[j][0]

    # parameters initilization

    y_hat, A1 = L_layer_forward(X, parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters, y, y_hat, A1, X)

    Loss.append(-y * np.log(y_hat) - (1 - y)*np.log(1 - y_hat))

  print("Epoch - ", i+1, 'Loss -', np.array(Loss).mean())

parameters



Epoch -  1 Loss - 0.7103199085929446
Epoch -  2 Loss - 0.6991702892802629
Epoch -  3 Loss - 0.6991679314811485
Epoch -  4 Loss - 0.6991655746710999
Epoch -  5 Loss - 0.6991632188496667
Epoch -  6 Loss - 0.699160864016399
Epoch -  7 Loss - 0.6991585101708473
Epoch -  8 Loss - 0.6991561573125619
Epoch -  9 Loss - 0.6991538054410936
Epoch -  10 Loss - 0.6991514545559935
Epoch -  11 Loss - 0.6991491046568126
Epoch -  12 Loss - 0.6991467557431024
Epoch -  13 Loss - 0.6991444078144144
Epoch -  14 Loss - 0.6991420608703007
Epoch -  15 Loss - 0.6991397149103132
Epoch -  16 Loss - 0.6991373699340042
Epoch -  17 Loss - 0.6991350259409265
Epoch -  18 Loss - 0.6991326829306324
Epoch -  19 Loss - 0.6991303409026751
Epoch -  20 Loss - 0.699127999856608
Epoch -  21 Loss - 0.6991256597919842
Epoch -  22 Loss - 0.6991233207083575
Epoch -  23 Loss - 0.6991209826052818
Epoch -  24 Loss - 0.699118645482311
Epoch -  25 Loss - 0.6991163093389996
Epoch -  26 Loss - 0.699113974174902
Epoch -  27 Loss - 0.6991

{'W1': array([[0.09994267, 0.09984548],
        [0.09994272, 0.09984548]]),
 'b1': array([[-3.38405750e-05],
        [-3.38419977e-05]]),
 'W2': array([[0.09920806],
        [0.09920816]]),
 'b2': array([[0.09915209]])}

### With Keras

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [ ]:
df

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

model.add(Dense(2, activation = 'sigmoid', input_dim=2))
model.add(Dense(1, activation = 'sigmoid'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.get_weights()

[array([[-0.02830112,  0.06220138],
        [-0.8734666 , -0.43202186]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.25792015],
        [-0.9278581 ]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
new_weights = [np.array([[0.1,  0.1],
        [0.1 , 0.1]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[0.1],
        [0.1 ]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]

In [ ]:
model.set_weights(new_weights)

In [ ]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate=0.0001)
model.compile(loss='binary_crossentropy', optimizer=optimizer)

In [ ]:
model.fit(df.iloc[:, 0:-1].values, df['placed'].values, epochs=50, verbose=1, batch_size=1)

Epoch 1/50
4/4 [==============================] - 1s 3ms/step - loss: 0.6930
Epoch 2/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6930
Epoch 3/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6930
Epoch 4/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6930
Epoch 5/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6930
Epoch 6/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6930
Epoch 7/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6930
Epoch 8/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6930
Epoch 9/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6929
Epoch 10/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6930
Epoch 11/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6929
Epoch 12/50
4/4 [==============================] - 0s 3ms/step - loss: 0.6930
Epoch 13/50
4/4 [==============================] - 0s 3ms/step - loss: 0.