<a href="https://colab.research.google.com/github/Swinalwaghmare/Deep-Learning/blob/main/Backpropagation_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa', 'profile_score', 'lpa'])

In [ ]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

### Code from scratch

In [ ]:
def initialize_parameters(layer_dims):

  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1, L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))

  return parameters

In [ ]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [ ]:
def linear_forward(A_prev, W, b):

  Z = np.dot(W.T, A_prev) + b

  return Z

In [ ]:
# forward propagation
def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2

  for l in range(1, L+1):
    A_prev = A
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]

    #print("A" + str(l-1)+ ":", A_prev)
    #print("W" + str(l)+ ":", Wl)
    #print("b" + str(l)+ ":", bl)
    #print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    #print("A"+ str(l) + ":", A)
    #print("**"*20)

  return A, A_prev




In [ ]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # shape(No of feature, no. of training example)
y = df[['lpa']].values[0][0]

parameters = initialize_parameters([2,2,1])

y_hat, A1  = L_layer_forward(X, parameters)

A0: [[8]
 [8]]
W1: [[0.1 0.1]
 [0.1 0.1]]
b1: [[0.]
 [0.]]
----------------------------------------
A1: [[1.6]
 [1.6]]
****************************************
A1: [[1.6]
 [1.6]]
W2: [[0.1]
 [0.1]]
b2: [[0.]]
----------------------------------------
A2: [[0.32]]
****************************************


In [ ]:
y_hat = y_hat[0][0]
y_hat

0.32000000000000006

In [ ]:
A1

array([[1.6],
       [1.6]])

In [ ]:
def update_parameters(parameters, y, y_hat, A1, X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)* A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)* A1[1][0])
  parameters['b2'][0][0] = parameters['b2'][0][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])



In [ ]:
update_parameters(parameters, y, y_hat,A1, X)

In [ ]:
parameters

{'W1': array([[0.11385611, 0.1       ],
        [0.12771223, 0.11385611]]),
 'b1': array([[0.00090934],
        [0.        ]]),
 'W2': array([[0.123552],
        [0.123552]]),
 'b2': array([[0.01472]])}

In [ ]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # shape(No of feature, no. of training example)
y = df[['lpa']].values[1][0]



y_hat, A1  = L_layer_forward(X, parameters)

A0: [[7]
 [9]]
W1: [[0.11385611 0.1       ]
 [0.12771223 0.11385611]]
b1: [[0.00090934]
 [0.        ]]
----------------------------------------
A1: [[1.94731216]
 [1.72470501]]
****************************************
A1: [[1.94731216]
 [1.72470501]]
W2: [[0.123552]
 [0.123552]]
b2: [[0.01472]]
----------------------------------------
A2: [[0.46840507]]
****************************************


In [ ]:
update_parameters(parameters, y, y_hat,A1, X)

In [ ]:
parameters

{'W1': array([[0.12281422, 0.1       ],
        [0.14805991, 0.12520912]]),
 'b1': array([[0.00126144],
        [0.        ]]),
 'W2': array([[0.14120086],
        [0.13918333]]),
 'b2': array([[0.02378319]])}

In [ ]:
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1) # shape(No of feature, no. of training example)
y = df[['lpa']].values[2][0]



y_hat, A1  = L_layer_forward(X, parameters)

A0: [[ 6]
 [10]]
W1: [[0.12281422 0.1       ]
 [0.14805991 0.12520912]]
b1: [[0.00126144]
 [0.        ]]
----------------------------------------
A1: [[2.21874591]
 [1.85209117]]
****************************************
A1: [[2.21874591]
 [1.85209117]]
W2: [[0.14120086]
 [0.13918333]]
b2: [[0.02378319]]
----------------------------------------
A2: [[0.59485223]]
****************************************


In [ ]:
update_parameters(parameters, y, y_hat,A1, X)

In [ ]:
parameters

{'W1': array([[0.13352849, 0.1       ],
        [0.17624334, 0.14241965]]),
 'b1': array([[0.00172105],
        [0.        ]]),
 'W2': array([[0.16518616],
        [0.15920498]]),
 'b2': array([[0.03459349]])}

In [ ]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # shape(No of feature, no. of training example)
y = df[['lpa']].values[3][0]



y_hat, A1  = L_layer_forward(X, parameters)

A0: [[ 5]
 [12]]
W1: [[0.13352849 0.1       ]
 [0.17624334 0.14241965]]
b1: [[0.00172105]
 [0.        ]]
----------------------------------------
A1: [[2.7842836 ]
 [2.20903575]]
****************************************
A1: [[2.7842836 ]
 [2.20903575]]
W2: [[0.16518616]
 [0.15920498]]
b2: [[0.03459349]]
----------------------------------------
A2: [[0.8462081]]
****************************************


In [ ]:
update_parameters(parameters, y, y_hat,A1, X)

In [ ]:
parameters

{'W1': array([[0.14580247, 0.1       ],
        [0.21717113, 0.1699482 ]]),
 'b1': array([[0.00229405],
        [0.        ]]),
 'W2': array([[0.19945396],
        [0.18639287]]),
 'b2': array([[0.04690107]])}

In [ ]:
# epoch implementation

parameters = initialize_parameters([2,2,1])
epoch = 75

for i in range(epoch):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # shape(no of feature, no of training example)
    y = df[['lpa']].values[j][0]

    # parmeter initilization

    y_hat, A1 = L_layer_forward(X, parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y - y_hat)**2)

  print('Epoch -',i+1 ,'Loss -', np.array(Loss).mean())

parameters






Epoch - 1 Loss - 26.141253114181346
Epoch - 2 Loss - 18.61575866741753
Epoch - 3 Loss - 8.60971220546312
Epoch - 4 Loss - 2.2442137220249334
Epoch - 5 Loss - 0.6973601877999933
Epoch - 6 Loss - 0.5932555110032856
Epoch - 7 Loss - 0.6148696810405734
Epoch - 8 Loss - 0.6207092189784047
Epoch - 9 Loss - 0.6172348711758919
Epoch - 10 Loss - 0.6108562609598986
Epoch - 11 Loss - 0.6037149198926558
Epoch - 12 Loss - 0.5964270752847994
Epoch - 13 Loss - 0.5891628596923075
Epoch - 14 Loss - 0.5819678991017694
Epoch - 15 Loss - 0.574853511442414
Epoch - 16 Loss - 0.5678216156767456
Epoch - 17 Loss - 0.5608715835765806
Epoch - 18 Loss - 0.5540021224184082
Epoch - 19 Loss - 0.5472117916337849
Epoch - 20 Loss - 0.5404991439054861
Epoch - 21 Loss - 0.5338627630048947
Epoch - 22 Loss - 0.5273012732557321
Epoch - 23 Loss - 0.5208133412267812
Epoch - 24 Loss - 0.5143976753228614
Epoch - 25 Loss - 0.50805302483304
Epoch - 26 Loss - 0.5017781788632174
Epoch - 27 Loss - 0.4955719652686263
Epoch - 28 Loss 

{'W1': array([[0.02459582, 0.1       ],
        [0.53120994, 0.49655549]]),
 'b1': array([[0.00032262],
        [0.        ]]),
 'W2': array([[0.57388359],
        [0.45742862]]),
 'b2': array([[0.09422261]])}

### Keras Code

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

model.add(Dense(2, activation="linear",input_dim=2))
model.add(Dense(1, activation='linear'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.get_weights()

[array([[-0.99751747, -0.75007415],
        [-0.9610292 ,  0.27907562]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.10341048],
        [-0.46564007]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
new_weights = [np.array([[0.1, 0.1],
        [0.1 ,  0.1]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[0.1],
        [0.1]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]

In [ ]:
model.set_weights(new_weights)

In [ ]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [ ]:
model.fit(df.iloc[:,0:-1].values, df['lpa'].values, epochs=75, verbose=1, batch_size=1)

Epoch 1/75
4/4 [==============================] - 1s 5ms/step - loss: 27.8783
Epoch 2/75
4/4 [==============================] - 0s 3ms/step - loss: 27.5771
Epoch 3/75
4/4 [==============================] - 0s 5ms/step - loss: 27.2360
Epoch 4/75
4/4 [==============================] - 0s 4ms/step - loss: 26.8969
Epoch 5/75
4/4 [==============================] - 0s 4ms/step - loss: 26.5384
Epoch 6/75
4/4 [==============================] - 0s 4ms/step - loss: 26.1990
Epoch 7/75
4/4 [==============================] - 0s 4ms/step - loss: 25.8397
Epoch 8/75
4/4 [==============================] - 0s 4ms/step - loss: 25.4178
Epoch 9/75
4/4 [==============================] - 0s 4ms/step - loss: 25.0412
Epoch 10/75
4/4 [==============================] - 0s 4ms/step - loss: 24.6564
Epoch 11/75
4/4 [==============================] - 0s 6ms/step - loss: 24.2278
Epoch 12/75
4/4 [==============================] - 0s 4ms/step - loss: 23.8188
Epoch 13/75
4/4 [==============================] - 0s 5ms/ste

In [ ]:
model.get_weights()

[array([[0.37333888, 0.37333888],
        [0.36551514, 0.36551514]], dtype=float32),
 array([0.27213064, 0.27213064], dtype=float32),
 array([[0.37274238],
        [0.37274238]], dtype=float32),
 array([0.2047484], dtype=float32)]